/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gscope_main (void);
GtkWidget* create_aboutdialog1 (void);
GtkWidget* create_gscope_preferences (void);
GtkWidget* create_folder_chooser_dialog (void);
GtkWidget* create_open_file_chooser_dialog (void);
GtkWidget* create_output_file_chooser_dialog (void);
GtkWidget* create_quit_confirm_dialog (void);
GtkWidget* create_gscope_splash (void);
GtkWidget* create_stats_dialog (void);
GtkWidget* create_save_results_file_chooser_dialog (void);
